### ISSUE TITLE
hello_world.rbの編集

### ISSUE THREAD

**Issue by Hanason01** [Hanason01/leaf_repository#30]
hello_worldと表示する関数を定義し、ターミナルに`ruby hello_world.rb`コマンドでhello_worldと表示できるようにしてください。

**Comment by tmkimunida6** [comment]
お疲れ様です！
本件、対応してプルリクエスト送りました。
ご確認よろしくお願いします。

- [ ] https://github.com/Hanason01/leaf_repository/pull/33

**Comment by Hanason01** [comment]
お疲れさまです！ありがとうございます！
